//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Engineering.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_ja {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_ja() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Application.Engineering.Properties.Resources-ja", typeof(Resources_ja).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 詳細設定.
        /// </summary>
        public static string Advanced_Setup {
            get {
                return ResourceManager.GetString("Advanced_Setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to データベース.
        /// </summary>
        public static string Database {
            get {
                return ResourceManager.GetString("Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to テストを実行.
        /// </summary>
        public static string Execute_Test {
            get {
                return ResourceManager.GetString("Execute_Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to フォルダー.
        /// </summary>
        public static string Folders {
            get {
                return ResourceManager.GetString("Folders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 画像.
        /// </summary>
        public static string Images {
            get {
                return ResourceManager.GetString("Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 言語.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to レイアウト設定.
        /// </summary>
        public static string Layout_Setup {
            get {
                return ResourceManager.GetString("Layout_Setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ログ.
        /// </summary>
        public static string Logs {
            get {
                return ResourceManager.GetString("Logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ログフォルダー.
        /// </summary>
        public static string Logs_Folder {
            get {
                return ResourceManager.GetString("Logs_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 開く.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to データベースを開く.
        /// </summary>
        public static string Open_Database {
            get {
                return ResourceManager.GetString("Open_Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to レシピを開く.
        /// </summary>
        public static string Open_Recipe {
            get {
                return ResourceManager.GetString("Open_Recipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ビューを開く.
        /// </summary>
        public static string Open_View {
            get {
                return ResourceManager.GetString("Open_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to レシピを保存.
        /// </summary>
        public static string Save_Recipe {
            get {
                return ResourceManager.GetString("Save_Recipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ビューを保存.
        /// </summary>
        public static string Save_View {
            get {
                return ResourceManager.GetString("Save_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to セクション.
        /// </summary>
        public static string Sections {
            get {
                return ResourceManager.GetString("Sections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to セットアップ.
        /// </summary>
        public static string Setup {
            get {
                return ResourceManager.GetString("Setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 開始.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ログを表示する.
        /// </summary>
        public static string View_Logs {
            get {
                return ResourceManager.GetString("View_Logs", resourceCulture);
            }
        }
    }
}
